name = "privatelivesmatter-prod"
compatibility_date = "2025-10-03"
pages_build_output_dir = "./dist"

# Deploy with `wrangler pages deploy ./dist --project-name privatelivesmatter-prod --branch master`.
